ARG DATAFLOW_PYTHON_VERSION=3.9

FROM apache/beam_python${DATAFLOW_PYTHON_VERSION}_sdk:2.55.1

# Setup.
RUN mkdir -p /root
WORKDIR /root

ENV PYTHONPATH="/root:${PYTHONPATH}"

# Introduce the minimum set of files for install.
COPY README.md README.md
# For Dataflow with GPU, Package versions are different than original axlearn (need to be compatible with python 3.8)
COPY pyproject.dfgpu.toml pyproject.toml
#COPY axlearn/axlearn/cloud/gcp/examples/ .
#RUN ls -la /axlearn/axlearn/cloud/gcp/examples/*
RUN mkdir axlearn && touch axlearn/__init__.py

# Beam workers default to creating a new virtual environment on startup, thus
# we do installation into the global environment.
# Install dependencies.
RUN pip install flit
RUN pip install --upgrade pip

'''
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        apt-transport-https \
        ca-certificates \
        curl \
        gcc \
        g++ && \
    rm -rf /var/lib/apt/lists/*
'''

# Update package lists and upgrade installed packages
RUN apt-get update && \
    apt-get dist-upgrade -y && \
    rm -rf /var/lib/apt/lists/*

# Install NVIDIA CUDA 11.8
# Add NVIDIA package repositories
RUN curl -fsSL https://developer.download.nvidia.com/cuda/ubuntu2204/cuda-keyring_1.0-1_all.deb \
    | debian-fronten=noninteractive dpkg -i -
RUN echo "deb  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  /" > /etc/apt/sources.list.d/cuda.list
RUN apt-get update

# Install CUDA 11.8
RUN apt-get install -y --no-install-recommends \
    cuda-11-8 \
    libcudnn8=8.6.0.163-1+cuda11.8 \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for CUDA
ENV PATH /usr/local/cuda-11.8/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/cuda-11.8/lib64:${LD_LIBRARY_PATH}

'''
# Install Python tools for Ubuntu 22.04
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3.9-venv && \
    rm -rf /var/lib/apt/lists/*

# Setup venv to suppress pip warnings.
ENV VIRTUAL_ENV=/opt/venv39
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ENV RUN_PYTHON_SDK_IN_DEFAULT_ENVIRONMENT=1

# Copy the Apache Beam worker dependencies from the Beam Python 3.8 SDK image.
COPY --from=apache/beam_python3.9_sdk:2.55.1 /opt/apache/beam /opt/apache/beam
# Set the entrypoint to Apache Beam SDK worker launcher.
ENTRYPOINT [ "/opt/apache/beam/boot" ]
'''


#gpu packages are my own specified list (see pyproject.toml)
RUN pip install .[gcp,dataflow,dev] 
COPY . .
